project_id = "nosobqpiqhskkcfefbuw"

[functions.create-first-admin]
verify_jwt = false

[functions.generate-tryon]
verify_jwt = false

[functions.replicate-webhook]
verify_jwt = false

[functions.deploy-functions]
verify_jwt = false

[functions.health-check]
verify_jwt = false
